services:
  bot:
    build: .
    container_name: salembot
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    command: python src/main.py

  db:
    image: postgres:15
    container_name: salem-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
